# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G -Dfabric.loom.remapSources=false -Dloom.remapSources=false
org.gradle.parallel=true
org.gradle.java.home=C:/Users/devus/.jdks/jdk-25.0.4.1+1

# Fabric Properties
minecraft_version=26.3
yarn_mappings=26.3+build.1
loader_version=0.19.5
loom_version=1.18-SNAPSHOT

# Mod Properties
mod_version=0.8
maven_group=org.vortex.resourceloader
archives_base_name=resourceloader

# Fabric API
fabric_api_version=0.161.0+26.3
fabric.loom.remapSources=false
loom.remapSources=false
